# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac4860bf6b0129a42e29fa0544ee536b63afd7f8a3428e9a934ca79d471981d0d6475a60a0d8240c14a9d01531b6b428d17c359f62f16288e6bfe2a572052564

test:
  secret_key_base: 9958a467b7f155b117f0c81b5aa6b3e0e53e2886741c5991c9b30aeb4674149f7596f320236ef44196c3aca9718a1e71173e596a3a18cfeba11ed96081f07cfc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
